"""Report export utilities (Markdown and JSON)."""

from __future__ import annotations

from mas.schemas.report import ComplianceReport


def to_json(report: ComplianceReport, indent: int = 2) -> str:
    """Serialize a ComplianceReport to JSON."""
    return report.model_dump_json(indent=indent)


def to_markdown(report: ComplianceReport) -> str:
    """Render a ComplianceReport as a human-readable Markdown document."""
    lines: list[str] = []
    cls = report.classification
    flags = report.asset_flags
    comp = report.compliance_flags

    lines.append("# MiCAR Compliance Report")
    lines.append("")
    lines.append(f"**Classification:** `{cls.micar_class.value.upper()}`")
    lines.append(
        f"**Compliance Score:** {report.compliance_score:.1%} "
        f"({report.fulfilled_count}/{report.total_disclosures})"
    )
    lines.append(f"**Model:** {report.model_id}")
    lines.append(f"**Prompt Version:** {report.prompt_version}")
    lines.append(f"**Input Hash:** `{report.input_hash[:16]}...`")
    lines.append(f"**Timestamp:** {report.timestamp.isoformat()}")
    lines.append("")

    # Classification reasoning
    lines.append("## Classification")
    lines.append("")
    lines.append(f"**Triggered Rules:** {', '.join(cls.triggered_rules)}")
    lines.append(f"**Explanation:** {cls.explanation}")
    lines.append("")

    # Asset flags
    lines.append("## Asset Flags")
    lines.append("")
    lines.append("| Flag | Value | Confidence | Evidence |")
    lines.append("|------|-------|------------|----------|")
    for name in type(flags).model_fields:
        flag = getattr(flags, name)
        icon = "True" if flag.value else "False"
        evidence_short = flag.evidence[:80] + "..." if len(flag.evidence) > 80 else flag.evidence
        lines.append(f"| `{name}` | {icon} | {flag.confidence:.0%} | {evidence_short} |")
    lines.append("")

    # Disclosure checklist
    lines.append("## Disclosure Checklist")
    lines.append("")
    lines.append(f"**Asset Class:** `{comp.micar_class}`")
    lines.append("")
    lines.append("| Requirement | Fulfilled | Confidence | Evidence |")
    lines.append("|-------------|-----------|------------|----------|")
    for d in comp.disclosures:
        icon = "Yes" if d.fulfilled else "No"
        evidence_short = d.evidence[:80] + "..." if len(d.evidence) > 80 else d.evidence
        lines.append(f"| `{d.requirement_id}` | {icon} | {d.confidence:.0%} | {evidence_short} |")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by MiCAR Compliance Agent*")

    return "\n".join(lines)
